### ISSUE TITLE
Error Node.js 20.x

### ISSUE THREAD

**Issue by SoulL3Zz** [Sinclair81/Homebridge-Logo-Platform#16]
Hi, I'm getting an error message since I upgraded to Node.js 20.x:

[10/26/2023, 10:43:53 AM] ====================
[10/26/2023, 10:43:53 AM] ERROR LOADING PLUGIN homebridge-logo-platform:
[10/26/2023, 10:43:53 AM] Error: The module '/var/lib/homebridge/node_modules/homebridge-logo-platform/node_modules/node-snap7/build/Release/node_snap7.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 115. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1327:18)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at bindings (/var/lib/homebridge/node_modules/homebridge-logo-platform/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-logo-platform/node_modules/node-snap7/lib/node-snap7.js:8:45)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-logo-platform/src/snap7-logo.ts:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
[10/26/2023, 10:43:53 AM] ====================

**Comment by Sinclair81** [comment]
That's not good to hear. I had installed the latest homebridge package on my development homebride especially for testing.
There is Node.js v18.18.2. With v16.3.0 everything works normally.
I'm not sure there's much I can do about it.

**Comment by Sinclair81** [comment]
If you don't have any old LOGO!s (0BA7 and 0BA8) try installing version **1.3.5.**
I switched off the Snap7 communication with the old LOGO!s.
But I will continue to look for a way to get Snap7 up to date.

**Comment by Sinclair81** [comment]
Node-snap7 is too old.
I was unable to install node-snap7 with its dev dependencies on my 2nd Homebridge development device.

But I found another snap7 module, [napi-snap7](https://github.com/fabioriva/napi-snap7).
I will try to test this and if it works I will install it instead of the node-snap7.

**Comment by AleVer254** [comment]
Hello, any update on this? My homebridge system is broken since the update. Or how can I revert back to the old version?

**Comment by Sinclair81** [comment]
I don't think there is a way back to an old version. If everything works, the update to 1.3.8 with napi-snap7 will come this afternoon.

**Comment by Sinclair81** [comment]
Unfortunately, I have bad news: during the first test of napi-snap7 I discovered that there was a small error in napi-snp7. I have created a PR with the solution, but now I have to wait until it is adopted.

**Comment by Sinclair81** [comment]
Once Fabio has uploaded his napi-snap7 (v1.2.3) to npm I can publish the next version. I tested them with NodeJS v20.5.1 (v20.7.0 would be better) and NPM v10.2.3.

**Comment by Sinclair81** [comment]
v1.4.0 with napi-snap7 instead of node-snap7 is out!
It now runs on Node.js 18.x and 20.x!

**Comment by blatorone** [comment]
After update on 1.4.0 I can’t use my blinds now. Tested with both nodes 18 and 20. switch is ok but every word value isn’t  working. Single bit values is ok
